name: cumbia_live_company
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # modal_bottom_sheet: ^3.0.0-pre
  uuid:
  google_fonts: ^6.2.1
  dio:
  url_launcher:
  #flutter_native_splash: ^1.3.2
  flutter_native_splash:
  flutter_animated_dialog_updated: ^1.0.1
  syncfusion_flutter_pdfviewer:
  easy_stepper:
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  dotted_border: ^2.0.0
  time_picker_spinner: ^1.0.2
  encrypt:
  #Stream Library
  zego_express_engine: ^3.21.0

  #Firebase dependencies
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_auth:
  firebase_core_platform_interface:
  visibility_detector:
  #  video_player: ^2.7.0
  chewie:
  file_picker: ^10.2.0
  modal_bottom_sheet:

  flutter_animate:
  responsive_builder: ^0.7.0
  get: ^4.7.2
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.2.3
  http: ^1.3.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  #flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/img/check.png
    - assets/img/logo.png
    - assets/img/placeholder.png
    - assets/img/icon.png
    - assets/img/logowhite.png
    - assets/img/loginBG.jpg
    - assets/img/bgPhone.png
    - assets/img/createAccountBG.jpg
    - assets/img/bgPhoneNew.png
    - assets/img/error.png
    - assets/img/photo_1.png
    - assets/img/photo_2.png
    - assets/pdf/privacy.pdf
    - assets/img/aprobado.png
    - assets/img/applogo.png
    - assets/img/Vector.png
    - assets/img/document.png
    - assets/img/Group.png
    - assets/img/settings.png
    - assets/img/Frame.png
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/font/bold.otf
          weight: 700
          style: normal
        - asset: assets/font/book.otf
          weight: 400
          style: normal
        - asset: assets/font/light.otf
          weight: 300
          style: normal
